version: "3.8"

services:
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:c85eb732f0ae9e4152b76c2d7da26e50c1fb54c05d9723800c198385ff66c247
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/transmission/config:/config
      - /mnt/user/plex/torrent:/plex/torrent
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
