version: "3.8"

services:
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:6b78970a0cb00709d3817fcb47b7cf74da56a43384bbd50d03955ca87e38c5f0
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/transmission/config:/config
      - /mnt/user/plex/torrent:/plex/torrent
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
