version: "3.8"

services:
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:30d59b253993df8c7634fe03cbb33e22324d00d200ff3d3cc30e6184fa55f96b
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/transmission/config:/config
      - /mnt/user/plex/torrent:/plex/torrent
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
