version: "3.8"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest@sha256:3950b5e48cf4ba9dab78fe14038dd7f062e66b7b4ab368b02c94a13f6a3dae9f
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/prowlarr/data:/config
    ports:
      - "9696:9696"
