version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest@sha256:f79738b25b19d8e11658e3f2233067732023a1ab2ead8be610d75c55e425ecb8
    container_name: plex
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - VERSION=latest
      - PLEX_CLAIM= #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/plex/config:/config
      - /mnt/nas/plex/Movies:/movies
      - /mnt/nas/plex/TV:/tv
      - /mnt/nas/plex/Sports:/sports
      - /mnt/nas/plex/Movies4k:/movies4k
      - /mnt/nas/plex/MoviesNew:/moviesNew
    runtime: nvidia
    restart: unless-stopped
