version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest@sha256:5a2dca89f4b53222ba2565ffa9ede3f320f37a69ac4b7fd475b492f772c5523b
    container_name: plex
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - VERSION=latest
      - PLEX_CLAIM= #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/plex/config:/config
      - /mnt/nas/plex/Movies:/movies
      - /mnt/nas/plex/TV:/tv
      - /mnt/nas/plex/Sports:/sports
      - /mnt/nas/plex/Movies4k:/movies4k
      - /mnt/nas/plex/MoviesNew:/moviesNew
    runtime: nvidia
    restart: unless-stopped
