apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          image: lscr.io/linuxserver/overseerr:latest
          ports:
            - containerPort: 5055
          env:
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - name: overseerr-storage
              mountPath: /config
      volumes:
        - name: overseerr-storage
          persistentVolumeClaim:
            claimName: overseerr-pvc