http:
  routers:
    nzbget:
      rule: "Host(`nzbget.home.shaunoneill.com`)"
      entryPoints:
        - websecure
      service: nzbget
      tls:
        certResolver: myresolver

  services:
    nzbget:
      loadBalancer:
        servers:
          - url: "http://192.168.0.10:6789"
