http:
  routers:
    proxmox:
      rule: "Host(`proxmox.home.shaunoneill.com`)"
      entryPoints:
        - websecure
      service: proxmox
      tls:
        certResolver: myresolver

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.0.200:8006"
        serversTransport: proxmox-insecure

  serversTransports:
    proxmox-insecure:
      insecureSkipVerify: true
