http:
  routers:
    wireguard:
      rule: "Host(`wireguard.home.shaunoneill.com`)"
      entryPoints:
        - websecure
      service: wireguard
      tls:
        certResolver: myresolver

  services:
    wireguard:
      loadBalancer:
        servers:
          - url: "http://192.168.0.10:51821"
