version: "3.8"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:v1.6.0-ls361
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/bazarr/config:/config
      - /mnt/user/plex:/plex
    ports:
      - "6767:6767"
