version: "3.8"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest@sha256:047222423d6d8556a88581b189175bec57f286f120b52ba29c0390fe6babaa5a
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/bazarr/config:/config
      - /mnt/user/plex:/plex
    ports:
      - "6767:6767"
