version: "3.8"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest@sha256:4c30dc0bb9a5d223075e7f5d12c77bd293c4b460f86d696dbe64763104c1e88c
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/bazarr/config:/config
      - /mnt/user/plex:/plex
    ports:
      - "6767:6767"
