services:
  mc:
    image: itzg/minecraft-server:latest@sha256:d209013e65134d9c6aa0c962e81ddf1214efa733a4eec81d5d079b1b49c0a598
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "1536M"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      FORCE_GAMEMODE: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      VIEW_DISTANCE: "6"
    volumes:
      - "/opt/minecraft/data:/data"
