services:
  mc:
    image: itzg/minecraft-server:latest@sha256:2e7c7b7641a8f30e70fa8d357bc2ad1c029cb56c93ca7f39af08713166c755ca
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "1536M"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      FORCE_GAMEMODE: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      VIEW_DISTANCE: "6"
    volumes:
      - "/opt/minecraft/data:/data"
