services:
  mc:
    image: itzg/minecraft-server:latest@sha256:b97e8fd93f42c3ab796b135251bd07a9cb2f95d7b459b32eac81983ba70fbc91
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "1536M"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      FORCE_GAMEMODE: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      VIEW_DISTANCE: "6"
    volumes:
      - "/opt/minecraft/data:/data"
