version: "3.8"

services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest@sha256:20439658454cbe39f8be90b7d8e5027340c7f7ce99e3cac151992acd15785303
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/nzbget/config:/config
      - /mnt/user/plex/usenet:/plex/usenet
    ports:
      - "6789:6789"
