version: "3.8"

services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest@sha256:d79a67d21cf63431d9e08e7f10c920ef1f68f06e61c015e602c2c3f79d28a0ac
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/nzbget/config:/config
      - /mnt/user/plex/usenet:/plex/usenet
    ports:
      - "6789:6789"
