version: "3.8"

services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest@sha256:1dca6a4407e08313919d2780bf2a6bc17e21b947a6e8e34624b9e115795fcf8c
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Dublin
    volumes:
      - /mnt/user/shared/services/nzbget/config:/config
      - /mnt/user/plex/usenet:/plex/usenet
    ports:
      - "6789:6789"
