apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
        - name: nginx-proxy-manager
          image: jc21/nginx-proxy-manager:2.12.1
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 81
          env:
            - name: TZ
              value: Etc/UTC
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
          volumeMounts:
            - name: longhorn-vol-data
              mountPath: /data
            - name: longhorn-vol-letsencrypt
              mountPath: /etc/letsencrypt
      volumes:
        - name: longhorn-vol-data
          persistentVolumeClaim:
            claimName: nginx-proxy-manager-data
        - name: longhorn-vol-letsencrypt
          persistentVolumeClaim:
            claimName: nginx-proxy-manager-letsencrypt
