apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
        - name: nginx-proxy-manager
          image: 'jc21/nginx-proxy-manager:latest'
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 81
          env:
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - name: npm-vol-data
              mountPath: /data
            - name: npm-vol-letsencrypt
              mountPath: /etc/letsencrypt
      volumes:
        - name: npm-vol-data
          persistentVolumeClaim:
            claimName: npm-pvc
        - name: npm-vol-letsencrypt
          persistentVolumeClaim:
            claimName: npm-pvc
            