apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nginx-proxy-manager
  resources:
    requests:
      storage: 3Gi