apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
    spec:
      containers:
        - name: wg-easy
          image: ghcr.io/wg-easy/wg-easy:14
          env:
            - name: WG_HOST
              value: local.home.shaunoneill.com
            - name: PASSWORD_HASH
              value: '$2a$12$qVxNpGqe52Y2P2eUuRUxJuvh0WsStDdj7qTaDVD3ZD781R3qEo0KC'
            - name: WG_PORT
              value: "51820"
            - name: WG_DEFAULT_DNS
              value: "192.168.0.10"
          ports:
            - containerPort: 51820
              protocol: UDP
            - containerPort: 51821
              protocol: TCP
          volumeMounts:
            - name: wireguard-data
              mountPath: /etc/wireguard
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          sysctls:
            - name: net.ipv4.ip_forward
              value: "1"
            - name: net.ipv4.conf.all.src_valid_mark
              value: "1"
      volumes:
        - name: wireguard-data
          persistentVolumeClaim:
            claimName: wireguard-pvc
