apiVersion: v1
kind: Service
metadata:
  name: wg-easy-service
  namespace: default
spec:
  selector:
    app: wg-easy
  type: NodePort
  ports:
    - name: udp-port
      port: 51820
      targetPort: 51820
      nodePort: 30000
      protocol: UDP
    - name: admin-port
      port: 51821
      targetPort: 51821
      nodePort: 30001
      protocol: TCP

