apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  selector:
    app: plex
  type: LoadBalancer  # or LoadBalancer if you're using MetalLB or similar
  loadBalancerIP: 192.168.0.85
  ports:
    - port: 32400
      targetPort: 32400
