apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
        - name: tautulli
          image: ghcr.io/linuxserver/tautulli:2.15.1
          ports:
            - containerPort: 8181
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/London"
          volumeMounts:
            - name: tautulli-config
              mountPath: /config
      volumes:
        - name: tautulli-config
          persistentVolumeClaim:
            claimName: tautulli-config-pvc
  restartPolicy: Always
