apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:5.10.4-develop
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/London"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: plex-media
              mountPath: /plex
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: plex-media
          nfs:
            server: 192.168.0.10
            path: /mnt/user/plex
  restartPolicy: Always