services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped

    network_mode: host

    environment:
      - PORT=51821
      - INSECURE=true

    volumes:
      - /mnt/user/appdata/wg-easy:/etc/wireguard

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
