apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:next
          ports:
            - containerPort: 5678
          env:
            - name: TZ
              value: Etc/UTC
            - name: N8N_SECURE_COOKIE
              value: "false"
          volumeMounts:
            - name: n8n-storage
              mountPath: /opt/n8b/data
      volumes:
        - name: n8n-storage
          hostPath:
            path: /opt/n8n
            type: Directory