apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:next
          ports:
            - containerPort: 5678
          env:
            - name: TZ
              value: Etc/UTC
            - name: N8N_SECURE_COOKIE
              value: "false"
          volumeMounts:
            - name: nfs-vol
              mountPath: /home/node/.n8n
      volumes:
        - name: nfs-vol
          nfs:
            server: 192.168.0.10
            path: /mnt/user/shared/k8s/n8n